### PR TITLE
readme-update-commands

### PR DESCRIPTION
**Pull request by billythakidd04**
Updating the README file with a cheatsheet for all the useful commands we use daily.

### CODE REVIEW

**Review by vricci518 — APPROVED** [review]

**Review by margeschrec — APPROVED** [review]

**Review by CharleswithLove — APPROVED** [review]
thank you Bill

**Review by ghost — APPROVED** [review]

**Review by rbaia28 — APPROVED** [review]
Thank you!

**Review by tfrazzini13 — APPROVED** [review]
thank you

**Review by nburd90 — APPROVED** [review]

**Review by cwlainson — APPROVED** [review]

**Review by vricci518 — APPROVED** [review]
#20

**Review by gc824 — APPROVED** [review]

**Review by WaymonBrown84 — COMMENTED** [review]
thank you

**Pull request merged**
