### PR TITLE
Popquiz 0225

### PR DESCRIPTION
**Pull request by billythakidd04**
Added the questions and answers from quiz on 2/25
Please check your answers and make sure they are correct. If not please request changes with the correct answer in the comment

### CODE REVIEW

**Review by nburd90 — APPROVED** [review]

**Review by margeschrec — APPROVED** [review]

**Review by rbaia28 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by cwlainson — APPROVED** [review]
'twas the answer i gave.

**Review by vricci518 — APPROVED** [review]
My answer is correct #21

**Review by gc824 — APPROVED** [review]

**Review by tfrazzini13 — APPROVED** [review]

**Review by WaymonBrown84 — APPROVED** [review]
ok

**Review by CharleswithLove — APPROVED** [review]
correct !!!

**Pull request merged**
